from __future__ import print_function


virdis='virdis'
plasma='plasma'
inferno='inferno'
magma='magma'
greys='Greys'
purples='Purples'
blues='Blues'
greens='Greens'
oranges='Oranges'
reds='Reds'
yellowOrangeBrown='YlOrBr'
yellowOrangeRed='YlOrRd'
orangeRed='OrRd'
purpleRed='purpleRed'
redPurple='RdPu'
bluePurple='BuPu'
greenBlue='GnBu'
purpleBlue='PuBu'
yellowGreenBlue='YlGnBu'
purpleBlueGreen='PuBuGn'
blueGreen='BlueGreen'
yellowGreen='YlGn'

