# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LadybugVizzzNew.ui'
#
# Created: Tue Oct 24 17:03:45 2017
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1123, 753)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/images/log")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1121, 711))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tbMain = QtGui.QWidget()
        self.tbMain.setObjectName(_fromUtf8("tbMain"))
        self.txtWeatherDataDetails = QtGui.QTextEdit(self.tbMain)
        self.txtWeatherDataDetails.setGeometry(QtCore.QRect(300, 20, 211, 61))
        self.txtWeatherDataDetails.setObjectName(_fromUtf8("txtWeatherDataDetails"))
        self.webView = QtWebKit.QWebView(self.tbMain)
        self.webView.setGeometry(QtCore.QRect(300, 160, 811, 521))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.lblWeatherDataDetails = QtGui.QLabel(self.tbMain)
        self.lblWeatherDataDetails.setGeometry(QtCore.QRect(300, 0, 211, 20))
        self.lblWeatherDataDetails.setObjectName(_fromUtf8("lblWeatherDataDetails"))
        self.btnGeneratePlots = QtGui.QPushButton(self.tbMain)
        self.btnGeneratePlots.setGeometry(QtCore.QRect(0, 650, 291, 31))
        self.btnGeneratePlots.setObjectName(_fromUtf8("btnGeneratePlots"))
        self.lblGoogleMap = QtGui.QLabel(self.tbMain)
        self.lblGoogleMap.setGeometry(QtCore.QRect(300, 140, 101, 20))
        self.lblGoogleMap.setObjectName(_fromUtf8("lblGoogleMap"))
        self.radioWeatherUpload = QtGui.QRadioButton(self.tbMain)
        self.radioWeatherUpload.setGeometry(QtCore.QRect(90, 10, 181, 17))
        self.radioWeatherUpload.setObjectName(_fromUtf8("radioWeatherUpload"))
        self.radioWeatherSearch = QtGui.QRadioButton(self.tbMain)
        self.radioWeatherSearch.setGeometry(QtCore.QRect(90, 30, 201, 17))
        self.radioWeatherSearch.setObjectName(_fromUtf8("radioWeatherSearch"))
        self.btnUploadWeather = QtGui.QPushButton(self.tbMain)
        self.btnUploadWeather.setGeometry(QtCore.QRect(0, 70, 81, 31))
        self.btnUploadWeather.setObjectName(_fromUtf8("btnUploadWeather"))
        self.lblMode = QtGui.QLabel(self.tbMain)
        self.lblMode.setGeometry(QtCore.QRect(0, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lblMode.setFont(font)
        self.lblMode.setObjectName(_fromUtf8("lblMode"))
        self.lblWeatherUploadLocation = QtGui.QPlainTextEdit(self.tbMain)
        self.lblWeatherUploadLocation.setEnabled(False)
        self.lblWeatherUploadLocation.setGeometry(QtCore.QRect(90, 60, 201, 51))
        self.lblWeatherUploadLocation.setObjectName(_fromUtf8("lblWeatherUploadLocation"))
        self.lblSelectedEPWDetails = QtGui.QLabel(self.tbMain)
        self.lblSelectedEPWDetails.setGeometry(QtCore.QRect(530, 10, 571, 141))
        self.lblSelectedEPWDetails.setText(_fromUtf8(""))
        self.lblSelectedEPWDetails.setObjectName(_fromUtf8("lblSelectedEPWDetails"))
        self.btnConfirmWeatherData = QtGui.QPushButton(self.tbMain)
        self.btnConfirmWeatherData.setGeometry(QtCore.QRect(0, 610, 291, 28))
        self.btnConfirmWeatherData.setObjectName(_fromUtf8("btnConfirmWeatherData"))
        self.lblWeatherDataYearPlot = QtGui.QLabel(self.tbMain)
        self.lblWeatherDataYearPlot.setGeometry(QtCore.QRect(530, 20, 581, 131))
        self.lblWeatherDataYearPlot.setText(_fromUtf8(""))
        self.lblWeatherDataYearPlot.setObjectName(_fromUtf8("lblWeatherDataYearPlot"))
        self.grpSearchWeather = QtGui.QGroupBox(self.tbMain)
        self.grpSearchWeather.setGeometry(QtCore.QRect(-10, 120, 301, 491))
        self.grpSearchWeather.setTitle(_fromUtf8(""))
        self.grpSearchWeather.setObjectName(_fromUtf8("grpSearchWeather"))
        self.linEditLatitude = QtGui.QLineEdit(self.grpSearchWeather)
        self.linEditLatitude.setGeometry(QtCore.QRect(120, 50, 181, 22))
        self.linEditLatitude.setObjectName(_fromUtf8("linEditLatitude"))
        self.lblSearch = QtGui.QLabel(self.grpSearchWeather)
        self.lblSearch.setGeometry(QtCore.QRect(10, 20, 101, 20))
        self.lblSearch.setObjectName(_fromUtf8("lblSearch"))
        self.lblEPWlocations = QtGui.QLabel(self.grpSearchWeather)
        self.lblEPWlocations.setGeometry(QtCore.QRect(10, 150, 101, 20))
        self.lblEPWlocations.setObjectName(_fromUtf8("lblEPWlocations"))
        self.txtDownloadToLocation = QtGui.QPlainTextEdit(self.grpSearchWeather)
        self.txtDownloadToLocation.setEnabled(False)
        self.txtDownloadToLocation.setGeometry(QtCore.QRect(100, 430, 201, 51))
        self.txtDownloadToLocation.setObjectName(_fromUtf8("txtDownloadToLocation"))
        self.btnSearch = QtGui.QPushButton(self.grpSearchWeather)
        self.btnSearch.setGeometry(QtCore.QRect(10, 110, 291, 28))
        self.btnSearch.setObjectName(_fromUtf8("btnSearch"))
        self.btnDownloadTo = QtGui.QPushButton(self.grpSearchWeather)
        self.btnDownloadTo.setGeometry(QtCore.QRect(10, 440, 81, 31))
        self.btnDownloadTo.setObjectName(_fromUtf8("btnDownloadTo"))
        self.lblLatitude = QtGui.QLabel(self.grpSearchWeather)
        self.lblLatitude.setGeometry(QtCore.QRect(12, 50, 101, 20))
        self.lblLatitude.setObjectName(_fromUtf8("lblLatitude"))
        self.linEditLongitude = QtGui.QLineEdit(self.grpSearchWeather)
        self.linEditLongitude.setGeometry(QtCore.QRect(120, 80, 181, 22))
        self.linEditLongitude.setObjectName(_fromUtf8("linEditLongitude"))
        self.lblLongitude = QtGui.QLabel(self.grpSearchWeather)
        self.lblLongitude.setGeometry(QtCore.QRect(10, 80, 101, 20))
        self.lblLongitude.setObjectName(_fromUtf8("lblLongitude"))
        self.listEPWlocations = QtGui.QListWidget(self.grpSearchWeather)
        self.listEPWlocations.setGeometry(QtCore.QRect(10, 170, 291, 151))
        self.listEPWlocations.setObjectName(_fromUtf8("listEPWlocations"))
        self.linEditSearch = QtGui.QLineEdit(self.grpSearchWeather)
        self.linEditSearch.setGeometry(QtCore.QRect(70, 20, 231, 22))
        self.linEditSearch.setObjectName(_fromUtf8("linEditSearch"))
        self.lblSelectedLocationDetails = QtGui.QLabel(self.grpSearchWeather)
        self.lblSelectedLocationDetails.setGeometry(QtCore.QRect(10, 320, 141, 20))
        self.lblSelectedLocationDetails.setObjectName(_fromUtf8("lblSelectedLocationDetails"))
        self.txtSelectedLocationDetails = QtGui.QPlainTextEdit(self.grpSearchWeather)
        self.txtSelectedLocationDetails.setGeometry(QtCore.QRect(10, 340, 291, 71))
        self.txtSelectedLocationDetails.setObjectName(_fromUtf8("txtSelectedLocationDetails"))
        self.tabWidget.addTab(self.tbMain, _fromUtf8(""))
        self.tbChart = QtGui.QWidget()
        self.tbChart.setObjectName(_fromUtf8("tbChart"))
        self.lblCharts = QtGui.QLabel(self.tbChart)
        self.lblCharts.setGeometry(QtCore.QRect(200, 10, 901, 661))
        self.lblCharts.setText(_fromUtf8(""))
        self.lblCharts.setObjectName(_fromUtf8("lblCharts"))
        self.cmbPlotType = QtGui.QComboBox(self.tbChart)
        self.cmbPlotType.setGeometry(QtCore.QRect(0, 20, 201, 22))
        self.cmbPlotType.setObjectName(_fromUtf8("cmbPlotType"))
        self.cmbColorScheme = QtGui.QComboBox(self.tbChart)
        self.cmbColorScheme.setGeometry(QtCore.QRect(0, 70, 201, 22))
        self.cmbColorScheme.setObjectName(_fromUtf8("cmbColorScheme"))
        self.lblPlotType = QtGui.QLabel(self.tbChart)
        self.lblPlotType.setGeometry(QtCore.QRect(0, 1, 71, 20))
        self.lblPlotType.setObjectName(_fromUtf8("lblPlotType"))
        self.lblColorScheme = QtGui.QLabel(self.tbChart)
        self.lblColorScheme.setGeometry(QtCore.QRect(0, 51, 91, 20))
        self.lblColorScheme.setObjectName(_fromUtf8("lblColorScheme"))
        self.lblFont = QtGui.QLabel(self.tbChart)
        self.lblFont.setGeometry(QtCore.QRect(0, 101, 91, 20))
        self.lblFont.setObjectName(_fromUtf8("lblFont"))
        self.cmbFont = QtGui.QComboBox(self.tbChart)
        self.cmbFont.setGeometry(QtCore.QRect(0, 120, 201, 22))
        self.cmbFont.setObjectName(_fromUtf8("cmbFont"))
        self.cmbChartAspectRatio = QtGui.QComboBox(self.tbChart)
        self.cmbChartAspectRatio.setGeometry(QtCore.QRect(0, 179, 201, 22))
        self.cmbChartAspectRatio.setObjectName(_fromUtf8("cmbChartAspectRatio"))
        self.lblChartAspectRatio = QtGui.QLabel(self.tbChart)
        self.lblChartAspectRatio.setGeometry(QtCore.QRect(0, 160, 101, 20))
        self.lblChartAspectRatio.setObjectName(_fromUtf8("lblChartAspectRatio"))
        self.linEditMinValue = QtGui.QLineEdit(self.tbChart)
        self.linEditMinValue.setGeometry(QtCore.QRect(0, 230, 91, 20))
        self.linEditMinValue.setObjectName(_fromUtf8("linEditMinValue"))
        self.linEditMaxValue = QtGui.QLineEdit(self.tbChart)
        self.linEditMaxValue.setGeometry(QtCore.QRect(100, 230, 101, 20))
        self.linEditMaxValue.setObjectName(_fromUtf8("linEditMaxValue"))
        self.tabWidget.addTab(self.tbChart, _fromUtf8(""))
        self.tbWindRose = QtGui.QWidget()
        self.tbWindRose.setObjectName(_fromUtf8("tbWindRose"))
        self.lblWindrose = QtGui.QLabel(self.tbWindRose)
        self.lblWindrose.setGeometry(QtCore.QRect(150, 60, 951, 591))
        self.lblWindrose.setText(_fromUtf8(""))
        self.lblWindrose.setObjectName(_fromUtf8("lblWindrose"))
        self.tabWidget.addTab(self.tbWindRose, _fromUtf8(""))
        self.tbSunPath = QtGui.QWidget()
        self.tbSunPath.setObjectName(_fromUtf8("tbSunPath"))
        self.labelSunpath = QtGui.QLabel(self.tbSunPath)
        self.labelSunpath.setGeometry(QtCore.QRect(10, 0, 711, 641))
        self.labelSunpath.setText(_fromUtf8(""))
        self.labelSunpath.setObjectName(_fromUtf8("labelSunpath"))
        self.tabWidget.addTab(self.tbSunPath, _fromUtf8(""))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1123, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionOrigin_Story = QtGui.QAction(MainWindow)
        self.actionOrigin_Story.setObjectName(_fromUtf8("actionOrigin_Story"))
        self.actionVisit_on_Github = QtGui.QAction(MainWindow)
        self.actionVisit_on_Github.setObjectName(_fromUtf8("actionVisit_on_Github"))
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionOrigin_Story)
        self.menuAbout.addAction(self.actionVisit_on_Github)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.actionExit, QtCore.SIGNAL(_fromUtf8("triggered()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Ladybugvizzz !", None))
        self.lblWeatherDataDetails.setText(_translate("MainWindow", "Weather Data Details", None))
        self.btnGeneratePlots.setText(_translate("MainWindow", "Visualize !", None))
        self.lblGoogleMap.setText(_translate("MainWindow", "Map", None))
        self.radioWeatherUpload.setToolTip(_translate("MainWindow", "Click this button to enable ", None))
        self.radioWeatherUpload.setText(_translate("MainWindow", "Upload a weather data file", None))
        self.radioWeatherSearch.setToolTip(_translate("MainWindow", "Click this radio button to enable the search functionality", None))
        self.radioWeatherSearch.setText(_translate("MainWindow", "Search for weather data file", None))
        self.btnUploadWeather.setText(_translate("MainWindow", "Upload from", None))
        self.lblMode.setText(_translate("MainWindow", "File Mode", None))
        self.btnConfirmWeatherData.setText(_translate("MainWindow", "Confirm Weather Data File", None))
        self.lblSearch.setText(_translate("MainWindow", "Search", None))
        self.lblEPWlocations.setText(_translate("MainWindow", "EPW Locations", None))
        self.btnSearch.setText(_translate("MainWindow", "Search!", None))
        self.btnDownloadTo.setText(_translate("MainWindow", "Download to", None))
        self.lblLatitude.setText(_translate("MainWindow", "Latitude", None))
        self.lblLongitude.setText(_translate("MainWindow", "Longitude", None))
        self.lblSelectedLocationDetails.setText(_translate("MainWindow", "Selected location details", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbMain), _translate("MainWindow", "Main", None))
        self.lblPlotType.setText(_translate("MainWindow", "Plot Type", None))
        self.lblColorScheme.setText(_translate("MainWindow", "Color Scheme", None))
        self.lblFont.setText(_translate("MainWindow", "Font", None))
        self.lblChartAspectRatio.setText(_translate("MainWindow", "Chart Aspect Ratio", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbChart), _translate("MainWindow", "Charts", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbWindRose), _translate("MainWindow", "Wind Rose", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tbSunPath), _translate("MainWindow", "SunPath", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuAbout.setTitle(_translate("MainWindow", "About", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionOrigin_Story.setText(_translate("MainWindow", "Origin Story!", None))
        self.actionVisit_on_Github.setText(_translate("MainWindow", "Visit on Github", None))

from PyQt4 import QtWebKit
import resources
